/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;
import java.awt.Color;
import java.awt.Point;
import regex.CustomFilter;

import javax.swing.UIManager;

/**
 *
 * @author strotz
 */
public class FrameMain extends javax.swing.JFrame {

    static Color oldColor, newColor;
    static int pegNumber, repeatNumber;
    static String pattern;
    
    private CustomFilter[] cf = new CustomFilter[3];
    
    public FrameMain() {
        initComponents();
        
        cf[0] = new CustomFilter("[0-9]+",3);
        cf[1] = new CustomFilter("[0-9]+", 3);
        cf[2] = new CustomFilter("[ON]+", 3);
        
        pegTextField = cf[0].adjustField(pegTextField);
        repeatTextField = cf[1].adjustField(repeatTextField);
        patternTextField = cf[2].adjustField(patternTextField);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FrameInfo = new javax.swing.JFrame();
        infoLabel = new javax.swing.JLabel();
        label1 = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();
        label3 = new javax.swing.JLabel();
        label4 = new javax.swing.JLabel();
        label5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        exitButton = new javax.swing.JButton();
        FrameOldColor = new javax.swing.JFrame();
        oldColorChooser = new javax.swing.JColorChooser();
        oldColorLabel1 = new javax.swing.JLabel();
        FrameNewColor = new javax.swing.JFrame();
        newColorChooser = new javax.swing.JColorChooser();
        newColorLabel1 = new javax.swing.JLabel();
        FrameVisual = new javax.swing.JFrame();
        PanelVisual = new DrawPanel();
        mainLabel2 = new javax.swing.JLabel();
        warningDialog1 = new javax.swing.JDialog();
        mainLabel3 = new javax.swing.JLabel();
        warningLabel1 = new javax.swing.JLabel();
        exitButton1 = new javax.swing.JButton();
        warningDialog2 = new javax.swing.JDialog();
        mainLabel4 = new javax.swing.JLabel();
        warningLabel2 = new javax.swing.JLabel();
        exitButton2 = new javax.swing.JButton();
        warningDialog3 = new javax.swing.JDialog();
        mainLabel5 = new javax.swing.JLabel();
        warningLabel3 = new javax.swing.JLabel();
        exitButton3 = new javax.swing.JButton();
        warningDialog4 = new javax.swing.JDialog();
        mainLabel6 = new javax.swing.JLabel();
        warningLabel4 = new javax.swing.JLabel();
        exitButton4 = new javax.swing.JButton();
        warningDialog5 = new javax.swing.JDialog();
        mainLabel7 = new javax.swing.JLabel();
        warningLabel5 = new javax.swing.JLabel();
        exitButton5 = new javax.swing.JButton();
        mainLabel = new javax.swing.JLabel();
        pegLabel = new javax.swing.JLabel();
        pegTextField = new javax.swing.JTextField();
        repeatLabel = new javax.swing.JLabel();
        repeatTextField = new javax.swing.JTextField();
        patternTextField = new javax.swing.JTextField();
        patternLabel = new javax.swing.JLabel();
        infoButton = new javax.swing.JButton();
        drawButton = new javax.swing.JButton();
        oldColorLabel = new javax.swing.JLabel();
        oldColorButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        newColorButton = new javax.swing.JButton();

        FrameInfo.setLocation(new java.awt.Point(0, 0));
        FrameInfo.setMinimumSize(new java.awt.Dimension(387, 170));
        FrameInfo.setResizable(false);
        FrameInfo.setSize(new java.awt.Dimension(387, 170));

        infoLabel.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        infoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        infoLabel.setText("Info");

        label1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        label1.setText("Number of Pegs: ");

        label2.setText("The number of pegs on the loom");

        label3.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        label3.setText("Repeat Number:");

        label4.setText("The number of times the pattern repeats");

        label5.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        label5.setText("Pattern:");

        jLabel1.setText("A pattern in the form O = Old, N = New (ONNO)");

        exitButton.setText("OK");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FrameInfoLayout = new javax.swing.GroupLayout(FrameInfo.getContentPane());
        FrameInfo.getContentPane().setLayout(FrameInfoLayout);
        FrameInfoLayout.setHorizontalGroup(
            FrameInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FrameInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(infoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(FrameInfoLayout.createSequentialGroup()
                        .addGroup(FrameInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(FrameInfoLayout.createSequentialGroup()
                                .addComponent(label1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label2))
                            .addGroup(FrameInfoLayout.createSequentialGroup()
                                .addComponent(label3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(label4))
                            .addGroup(FrameInfoLayout.createSequentialGroup()
                                .addComponent(label5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel1)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(FrameInfoLayout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(exitButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        FrameInfoLayout.setVerticalGroup(
            FrameInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(infoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FrameInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label1)
                    .addComponent(label2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FrameInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label3)
                    .addComponent(label4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FrameInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label5)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exitButton)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        FrameOldColor.setMinimumSize(new java.awt.Dimension(686, 465));
        FrameOldColor.setPreferredSize(new java.awt.Dimension(686, 465));
        FrameOldColor.setResizable(false);
        FrameOldColor.setSize(new java.awt.Dimension(686, 465));

        oldColorLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        oldColorLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        oldColorLabel1.setText("Select Old Color");

        javax.swing.GroupLayout FrameOldColorLayout = new javax.swing.GroupLayout(FrameOldColor.getContentPane());
        FrameOldColor.getContentPane().setLayout(FrameOldColorLayout);
        FrameOldColorLayout.setHorizontalGroup(
            FrameOldColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameOldColorLayout.createSequentialGroup()
                .addComponent(oldColorChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FrameOldColorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(oldColorLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        FrameOldColorLayout.setVerticalGroup(
            FrameOldColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FrameOldColorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(oldColorLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(oldColorChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        FrameNewColor.setMinimumSize(new java.awt.Dimension(686, 465));
        FrameNewColor.setPreferredSize(new java.awt.Dimension(686, 465));
        FrameNewColor.setResizable(false);

        newColorLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        newColorLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        newColorLabel1.setText("Select New Color");

        javax.swing.GroupLayout FrameNewColorLayout = new javax.swing.GroupLayout(FrameNewColor.getContentPane());
        FrameNewColor.getContentPane().setLayout(FrameNewColorLayout);
        FrameNewColorLayout.setHorizontalGroup(
            FrameNewColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameNewColorLayout.createSequentialGroup()
                .addComponent(newColorChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FrameNewColorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(newColorLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        FrameNewColorLayout.setVerticalGroup(
            FrameNewColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FrameNewColorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(newColorLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(newColorChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        FrameVisual.setMinimumSize(new java.awt.Dimension(612, 687));
        FrameVisual.setResizable(false);
        FrameVisual.setSize(new java.awt.Dimension(612, 687));

        PanelVisual.setPreferredSize(new java.awt.Dimension(600, 600));
        PanelVisual.setSize(new java.awt.Dimension(600, 600));

        javax.swing.GroupLayout PanelVisualLayout = new javax.swing.GroupLayout(PanelVisual);
        PanelVisual.setLayout(PanelVisualLayout);
        PanelVisualLayout.setHorizontalGroup(
            PanelVisualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        PanelVisualLayout.setVerticalGroup(
            PanelVisualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        mainLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        mainLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainLabel2.setText("Visual");

        javax.swing.GroupLayout FrameVisualLayout = new javax.swing.GroupLayout(FrameVisual.getContentPane());
        FrameVisual.getContentPane().setLayout(FrameVisualLayout);
        FrameVisualLayout.setHorizontalGroup(
            FrameVisualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameVisualLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FrameVisualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mainLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                    .addComponent(PanelVisual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        FrameVisualLayout.setVerticalGroup(
            FrameVisualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameVisualLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelVisual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(32, 32, 32))
        );

        warningDialog1.setMinimumSize(new java.awt.Dimension(285, 135));
        warningDialog1.setSize(new java.awt.Dimension(285, 135));

        mainLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        mainLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainLabel3.setText("Warning");

        warningLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        warningLabel1.setText("Please enter a number of pegs on the loom.");

        exitButton1.setText("OK");
        exitButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout warningDialog1Layout = new javax.swing.GroupLayout(warningDialog1.getContentPane());
        warningDialog1.getContentPane().setLayout(warningDialog1Layout);
        warningDialog1Layout.setHorizontalGroup(
            warningDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(warningDialog1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(warningDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mainLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(warningLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, warningDialog1Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(exitButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86)))
                .addContainerGap())
        );
        warningDialog1Layout.setVerticalGroup(
            warningDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(warningDialog1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(warningLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(exitButton1)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        warningDialog2.setMinimumSize(new java.awt.Dimension(285, 145));
        warningDialog2.setPreferredSize(new java.awt.Dimension(285, 145));
        warningDialog2.setResizable(false);
        warningDialog2.setSize(new java.awt.Dimension(285, 145));

        mainLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        mainLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainLabel4.setText("Warning");

        warningLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        warningLabel2.setText("Please enter the frequency of repeating.");

        exitButton2.setText("OK");
        exitButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout warningDialog2Layout = new javax.swing.GroupLayout(warningDialog2.getContentPane());
        warningDialog2.getContentPane().setLayout(warningDialog2Layout);
        warningDialog2Layout.setHorizontalGroup(
            warningDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(warningDialog2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(warningDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mainLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(warningLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, warningDialog2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(exitButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92))
        );
        warningDialog2Layout.setVerticalGroup(
            warningDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(warningDialog2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainLabel4)
                .addGap(18, 18, 18)
                .addComponent(warningLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(exitButton2)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        warningDialog3.setMinimumSize(new java.awt.Dimension(285, 145));
        warningDialog3.setPreferredSize(new java.awt.Dimension(285, 145));
        warningDialog3.setResizable(false);
        warningDialog3.setSize(new java.awt.Dimension(285, 145));

        mainLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        mainLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainLabel5.setText("Warning");

        warningLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        warningLabel3.setText("Pattern must repeat at least 2 squares.");

        exitButton3.setText("OK");
        exitButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout warningDialog3Layout = new javax.swing.GroupLayout(warningDialog3.getContentPane());
        warningDialog3.getContentPane().setLayout(warningDialog3Layout);
        warningDialog3Layout.setHorizontalGroup(
            warningDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(warningDialog3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(warningDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mainLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(warningLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, warningDialog3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(exitButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92))
        );
        warningDialog3Layout.setVerticalGroup(
            warningDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(warningDialog3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainLabel5)
                .addGap(18, 18, 18)
                .addComponent(warningLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(exitButton3)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        warningDialog4.setMinimumSize(new java.awt.Dimension(285, 145));
        warningDialog4.setPreferredSize(new java.awt.Dimension(285, 145));
        warningDialog4.setResizable(false);
        warningDialog4.setSize(new java.awt.Dimension(285, 145));

        mainLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        mainLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainLabel6.setText("Warning");

        warningLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        warningLabel4.setText("Please enter a pattern (ex. OONOO)");

        exitButton4.setText("OK");
        exitButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout warningDialog4Layout = new javax.swing.GroupLayout(warningDialog4.getContentPane());
        warningDialog4.getContentPane().setLayout(warningDialog4Layout);
        warningDialog4Layout.setHorizontalGroup(
            warningDialog4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(warningDialog4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(warningDialog4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mainLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(warningLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, warningDialog4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(exitButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92))
        );
        warningDialog4Layout.setVerticalGroup(
            warningDialog4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(warningDialog4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainLabel6)
                .addGap(18, 18, 18)
                .addComponent(warningLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(exitButton4)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        warningDialog5.setMinimumSize(new java.awt.Dimension(296, 145));
        warningDialog5.setPreferredSize(new java.awt.Dimension(296, 145));
        warningDialog5.setResizable(false);
        warningDialog5.setSize(new java.awt.Dimension(296, 145));

        mainLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        mainLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainLabel7.setText("Warning");

        warningLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        warningLabel5.setText("Repeat number and pattern length mismatch.");

        exitButton5.setText("OK");
        exitButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout warningDialog5Layout = new javax.swing.GroupLayout(warningDialog5.getContentPane());
        warningDialog5.getContentPane().setLayout(warningDialog5Layout);
        warningDialog5Layout.setHorizontalGroup(
            warningDialog5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(warningDialog5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(warningDialog5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mainLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(warningLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, warningDialog5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(exitButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92))
        );
        warningDialog5Layout.setVerticalGroup(
            warningDialog5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(warningDialog5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainLabel7)
                .addGap(18, 18, 18)
                .addComponent(warningLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(exitButton5)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        mainLabel.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        mainLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainLabel.setText("Loom Visualizer");

        pegLabel.setText("Number of Pegs");

        pegTextField.setToolTipText("How many pegs are on the loom?");

        repeatLabel.setText("Repeat Number");

        repeatTextField.setToolTipText("How often does the pattern repeat?");
        repeatTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                repeatTextFieldFocusLost(evt);
            }
        });

        patternTextField.setToolTipText("Example: ONNON");

        patternLabel.setText("Pattern");

        infoButton.setText("Info");
        infoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoButtonActionPerformed(evt);
            }
        });

        drawButton.setText("Draw");
        drawButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drawButtonActionPerformed(evt);
            }
        });

        oldColorLabel.setText("Old Color");

        oldColorButton.setText("Select");
        oldColorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oldColorButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("New Color");

        newColorButton.setText("Select");
        newColorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newColorButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mainLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pegLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pegTextField))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(repeatLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(patternLabel)
                                    .addComponent(oldColorLabel)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(infoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(8, 8, 8)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(patternTextField)
                            .addComponent(repeatTextField)
                            .addComponent(drawButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(oldColorButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(newColorButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pegLabel)
                    .addComponent(pegTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(repeatLabel)
                    .addComponent(repeatTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patternTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patternLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(oldColorLabel)
                    .addComponent(oldColorButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(newColorButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(infoButton)
                    .addComponent(drawButton))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void drawButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drawButtonActionPerformed
        if (pegTextField.getText().isBlank() || 
            Integer.parseInt(pegTextField.getText()) < 2) {
            warningDialog1.setLocation(new Point(this.getLocation().x,
            this.getLocation().y+this.getHeight()));
            warningDialog1.setVisible(true);
        } else if (repeatTextField.getText().isBlank()) {
            warningDialog2.setLocation(new Point(this.getLocation().x,
            this.getLocation().y+this.getHeight()));
            warningDialog2.setVisible(true);
        } else if (Integer.parseInt(repeatTextField.getText()) < 2) {
            warningDialog3.setLocation(new Point(this.getLocation().x,
            this.getLocation().y+this.getHeight()));
            warningDialog3.setVisible(true);
        } else if (patternTextField.getText().isBlank()) {
            warningDialog4.setLocation(new Point(this.getLocation().x,
            this.getLocation().y+this.getHeight()));
            warningDialog4.setVisible(true);
        } else if (patternTextField.getText().length() != 
                Integer.parseInt(repeatTextField.getText())) {
            warningDialog5.setLocation(new Point(this.getLocation().x,
            this.getLocation().y+this.getHeight()));
            warningDialog5.setVisible(true);
        } else {
            pegNumber = Integer.parseInt(pegTextField.getText());
            repeatNumber = Integer.parseInt(repeatTextField.getText());
            pattern = patternTextField.getText();

            FrameInfo.setVisible(false);
            FrameOldColor.setVisible(false);
            FrameNewColor.setVisible(false);
            
            oldColor = oldColorChooser.getColor();
            newColor = newColorChooser.getColor();

            FrameVisual.repaint();
            if (!FrameVisual.isVisible())
                FrameVisual.setLocation(new Point(this.getLocation().x+this.getWidth(),
                this.getLocation().y));
            FrameVisual.setVisible(true);
        }
    }//GEN-LAST:event_drawButtonActionPerformed

    private void infoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoButtonActionPerformed
        FrameInfo.setLocation(new Point(this.getLocation().x+this.getWidth(),
            this.getLocation().y));
        FrameInfo.setVisible(true);
    }//GEN-LAST:event_infoButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        FrameInfo.setVisible(false);
    }//GEN-LAST:event_exitButtonActionPerformed

    private void oldColorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oldColorButtonActionPerformed
        FrameOldColor.setVisible(true);
    }//GEN-LAST:event_oldColorButtonActionPerformed

    private void newColorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newColorButtonActionPerformed
        FrameNewColor.setVisible(true);
    }//GEN-LAST:event_newColorButtonActionPerformed

    private void repeatTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_repeatTextFieldFocusLost
        if (!repeatTextField.getText().isBlank()) {
            cf[2] = new CustomFilter("[ON]+", 
                    Integer.parseInt(repeatTextField.getText()));

            patternTextField = cf[2].adjustField(patternTextField);
        }
    }//GEN-LAST:event_repeatTextFieldFocusLost

    private void exitButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButton1ActionPerformed
        warningDialog1.setVisible(false);
    }//GEN-LAST:event_exitButton1ActionPerformed

    private void exitButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButton5ActionPerformed
        warningDialog5.setVisible(false);
    }//GEN-LAST:event_exitButton5ActionPerformed

    private void exitButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButton2ActionPerformed
        warningDialog2.setVisible(false);
    }//GEN-LAST:event_exitButton2ActionPerformed

    private void exitButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButton3ActionPerformed
        warningDialog3.setVisible(false);
    }//GEN-LAST:event_exitButton3ActionPerformed

    private void exitButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButton4ActionPerformed
        warningDialog4.setVisible(false);
    }//GEN-LAST:event_exitButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(
            UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameMain().setVisible(true);
            }
        });
    }
    
    static Color getOldColor() {
        return oldColor;
    }
    
    static Color getNewColor() {
        return newColor;
    }
    
    static int getPegNumber() {
        return pegNumber;
    }
    
    static int getRepeatNumber() {
        return repeatNumber;
    }
    
    static String getPattern() {
        return pattern;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame FrameInfo;
    private javax.swing.JFrame FrameNewColor;
    private javax.swing.JFrame FrameOldColor;
    private javax.swing.JFrame FrameVisual;
    private javax.swing.JPanel PanelVisual;
    private javax.swing.JButton drawButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton exitButton1;
    private javax.swing.JButton exitButton2;
    private javax.swing.JButton exitButton3;
    private javax.swing.JButton exitButton4;
    private javax.swing.JButton exitButton5;
    private javax.swing.JButton infoButton;
    private javax.swing.JLabel infoLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label4;
    private javax.swing.JLabel label5;
    private javax.swing.JLabel mainLabel;
    private javax.swing.JLabel mainLabel2;
    private javax.swing.JLabel mainLabel3;
    private javax.swing.JLabel mainLabel4;
    private javax.swing.JLabel mainLabel5;
    private javax.swing.JLabel mainLabel6;
    private javax.swing.JLabel mainLabel7;
    private javax.swing.JButton newColorButton;
    private javax.swing.JColorChooser newColorChooser;
    private javax.swing.JLabel newColorLabel1;
    private javax.swing.JButton oldColorButton;
    private javax.swing.JColorChooser oldColorChooser;
    private javax.swing.JLabel oldColorLabel;
    private javax.swing.JLabel oldColorLabel1;
    private javax.swing.JLabel patternLabel;
    private javax.swing.JTextField patternTextField;
    private javax.swing.JLabel pegLabel;
    private javax.swing.JTextField pegTextField;
    private javax.swing.JLabel repeatLabel;
    private javax.swing.JTextField repeatTextField;
    private javax.swing.JDialog warningDialog1;
    private javax.swing.JDialog warningDialog2;
    private javax.swing.JDialog warningDialog3;
    private javax.swing.JDialog warningDialog4;
    private javax.swing.JDialog warningDialog5;
    private javax.swing.JLabel warningLabel1;
    private javax.swing.JLabel warningLabel2;
    private javax.swing.JLabel warningLabel3;
    private javax.swing.JLabel warningLabel4;
    private javax.swing.JLabel warningLabel5;
    // End of variables declaration//GEN-END:variables
}
